### ISSUE TITLE
install_microk8s script not working

### ISSUE THREAD

**Issue by nyrahul** [SanjeevKGupta/example-kubearmor#1]
Not sure what parameters to use to create the micro-k8s cluster!

![image](https://github.com/SanjeevKGupta/example-kubearmor/assets/9133227/8a66ef22-2d00-4213-8a2e-7700174eb3eb)

Environment:
```
rahul@iZrj95btz9minp23m8evepZ:~/example-kubearmor/script$ hostnamectl
 Static hostname: iZrj95btz9minp23m8evepZ
       Icon name: computer-vm
         Chassis: vm
      Machine ID: 4661e99e696246fbab1e21a5b1b31874
         Boot ID: d35c286b5fdb408b8aaba064dcc31e89
  Virtualization: kvm
Operating System: Ubuntu 22.04.4 LTS
          Kernel: Linux 5.15.0-94-generic
    Architecture: x86-64
 Hardware Vendor: Alibaba Cloud
  Hardware Model: Alibaba Cloud ECS
```

**Comment by joewxboy** [comment]
I used `./install_microk8s.sh -c -n ubuntu` where "ubuntu" was the non-root userid.

If you've already attempted an install unsuccessfully, use the delete option first: `./install_microk8s.sh -d`

**Comment by SanjeevKGupta** [comment]
@nyrahul .. 
You should be logged in as a non-root user having sudo privilege.

**Comment by nyrahul** [comment]
No more a problem. Thanks @SanjeevKGupta @joewxboy
